
services:
  web:
    build: .
    command: gunicorn taskmanager.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - settings.env
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cactus_db
      POSTGRES_USER: cactus_user
      POSTGRES_PASSWORD: cactus_pass

volumes: {}
